theme: minima
title: Isaac Pena's Professional Portfolio
author: Isaac Pena
Description: This is a Professional Protfolio, for Isaac Pena and his research endevors. These endevors will explore the area of physics studied by Isaac and Classwork projects completed by Isaac. 



